name: Build & Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v4

      # 2. Install Node and deps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # 3. Build your Vite project
      - name: Build for production
        run: npm run build   # → creates the dist/ folder

      # 4. Deploy dist/ via FTP
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./dist/            # ← your built output
          server-dir: /public_html/
          git-ftp-args: --insecure      # remove if using FTPS/SFTP
